--SCRIPT PARA CREAR LA BASE DE DATOS.

CREATE DATABASE ResidenciasDB

USE ResidenciasDB

CREATE TABLE Academico(
ID INT NOT NULL PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL


)

CREATE TABLE Escolar(
ID INT NOT NULL PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL


)

CREATE TABLE DivisionDeEstudios(
ID INT NOT NULL PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL


)


CREATE TABLE TipoUsuario(
Usuario VARCHAR NOT NULL,
Password VARCHAR NOT NULL
)

CREATE TABLE Alumno(
NC INT NOT NULL PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Apellidos VARCHAR(50) NOT NULL,
Telefono INT NOT NULL,
Correo VARCHAR(50) NOT NULL
)

CREATE TABLE Asesor(
ID INT NOT NULL PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Apellidos VARCHAR(50) NOT NULL,
Telefono INT NOT NULL,
Correo VARCHAR(50) NOT NULL
)

CREATE TABLE Empresa(
ID INT NOT NULL PRIMARY KEY,
Nombre VARCHAR(50) NOT NULL,
Direccion VARCHAR(50),
Correo VARCHAR(50) NOT NULL,
Telefono INT NOT NULL
)

CREATE TABLE Proyecto(
NCAlumno INT NOT NULL FOREIGN KEY REFERENCES Alumno(NC),
IDEmpresa INT NOT NULL FOREIGN KEY REFERENCES Empresa(ID),
IDAsesor INT NOT NULL FOREIGN KEY REFERENCES Asesor(ID),
Fecha DATETIME NOT NULL,
EstadoProyecto INT NOT NULL
)


CREATE TABLE Reportes(
NCAlumno INT NOT NULL FOREIGN KEY REFERENCES Alumno(NC),
IDEmpresa INT NOT NULL FOREIGN KEY REFERENCES Empresa(ID),
IDAsesor INT NOT NULL FOREIGN KEY REFERENCES Asesor(ID),
Nombre VARCHAR(50) NOT NULL,
Apellidos VARCHAR(50) NOT NULL,
Descripcion VARCHAR(200) NOT NULL
)
